### PR TITLE
Repaired issue of wrong position

### PR DESCRIPTION
**Pull request by slord399**
Root of issue seems to be positioning data are incorrect, I tested myself it is working now.
You can try yourself before merging it.

### CODE REVIEW

**Comment by JLChnToZ** [comment]
It is better to state how you changed the data, because this will make the result unsync with the generator (the node.js project inside `tzmapper` directory)

**Comment by JLChnToZ** [comment]
For instance, if anyone needs to update to latest version and used the generator, they will get a bugged version again.

**Comment by slord399** [comment]
Sorry for missing context, I was in rush leaving office at the time.

Root cause of issue causing wrong location is actually are not suitable location data gathered by node.js + over the float limit of unity software .
(as some time zone position is set to on the sea instead on the land. there are several reason doing like this.)
*also I noticed if time zones on PC include multiple locations, it become center of these locations if it too close.
(for example is Dublin/Edinburgh/Lisbon/London on Windows OS)

Way to prevent this is either,
*If time zones got name of place within string, get position of that place instead of time zones flag position.
(I think you can do this exception by making other data collection method.)
or
*Manually find location's longitude and latitude to replace by themselves. (override way, but more accurate than current which I did.)

Both way got pos and con but it is possible to repair at least. (if user don't like to see their position on the wrong place.)

----

I also find data downloaded by node.js got too long digits which unity struggle to handle in some case.
To accommodate what we need for this project, it should be enough preciously with (-)XXX.YYYYY format.
I think you can add code on node.js to strip non necessary digits to prevent float issue of unity side.
(This option is basically making debug easier as need to separate what is causing this issue.)

**Comment by JLChnToZ** [comment]
As I know, the time zone names provided by Windows is not as same as IANA one (the one with city name), it usually indicates multiple regions of the IANA one. So what it did in Node.JS generator is try to group those regions using mapping table and find the centroid of that region as the pin point. Also, there is no way to getting more than the user's time zone region name in VRChat Udon VM as those methods are not exposed.

Reference on time zone names provided by Windows: https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-time-zones

I don't think the second way is the solution unless I give up to use that generator. It will be hard to maintain the time zone data table as I or other maintainers need to track the changes and manually adjust the coordinates on every update.

And the last one you are right, the digits could be strip down in Node.JS, I will commit that one to the codebase soon.

**Comment by slord399** [comment]
yeah, true. override method would works but hard to maintain.
I did it this time as I want to show off world on this weekend and place this Earth cube at entrance for display purpose.
(at least should works until they changed something to time zones name but no guarantee.)

**Comment by JLChnToZ** [comment]
I accepted the merge, but this is not the long-term solution, it still need to think about how to workaround with the generator.

**Pull request merged**
